//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Карта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Карта()
        {
            this.Записи_На_Прием = new HashSet<Записи_На_Прием>();
            this.Посещения = new HashSet<Посещения>();
        }
    
        public int Код_Карты { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<long> Телефон { get; set; }
        public System.DateTime Дата_рождения { get; set; }
        public Nullable<decimal> Страховой_Полис { get; set; }
        public string Диагноз { get; set; }
        public string Предоставленные_услуги { get; set; }
        public string Описание_приема { get; set; }
        
        public string ФИО { get { return Фамилия + " " + Имя + " " + Отчество; } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Записи_На_Прием> Записи_На_Прием { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Посещения> Посещения { get; set; }
    }
}
