//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посещения
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Посещения()
        {
            this.Оказанные_Услуги = new HashSet<Оказанные_Услуги>();
        }
    
        public int Код_Посещения { get; set; }
        public int Код_Диагноза { get; set; }
        public int Код_Карты { get; set; }
        public int Код_Записи { get; set; }
        public int Код_Услуги { get; set; }
    
        public virtual Диагноз Диагноз { get; set; }
        public virtual Карта Карта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оказанные_Услуги> Оказанные_Услуги { get; set; }
        public virtual Приемы Приемы { get; set; }
    }
}
