//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dentistry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int Код_Расписания { get; set; }
        public int Код_Врача { get; set; }
        public string Пн { get; set; }
        public string Вт { get; set; }
        public string Ср { get; set; }
        public string Чт { get; set; }
        public string Пт { get; set; }
        public string Сб { get; set; }
        public string Вс { get; set; }
        public string Кабинет { get; set; }
    
        public virtual Врачи Врачи { get; set; }
    }
}
